export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGIN_START = "LOGIN_START"
export const LOGIN_STOP = "LOGIN_STOP"

export const REGISTER_START = "REGISTER_START"
export const REGISTER_STOP = "REGISTER_STOP"